class IngredientTranslator {
  static final Map<String, String> _translations = {
    'pasta': 'makarna',
    'spaghetti': 'spagetti',
    'penne': 'penne',
    'fusilli': 'fusilli',
    'linguine': 'linguine',
    'fettuccine': 'fettuccine',
    'olive oil': 'zeytinyağı',
    'olive': 'zeytin',
    'olives': 'zeytin',
    'garlic': 'sarımsak',
    'onion': 'soğan',
    'onions': 'soğan',
    'tomato': 'domates',
    'tomatoes': 'domates',
    'salt': 'tuz',
    'pepper': 'karabiber',
    'black pepper': 'karabiber',
    'red pepper': 'kırmızı biber',
    'flour': 'un',
    'sugar': 'şeker',
    'butter': 'tereyağı',
    'milk': 'süt',
    'eggs': 'yumurta',
    'egg': 'yumurta',
    'cheese': 'peynir',
    'chicken': 'tavuk',
    'beef': 'sığır eti',
    'pork': 'domuz eti',
    'fish': 'balık',
    'rice': 'pirinç',
    'bread': 'ekmek',
    'potato': 'patates',
    'potatoes': 'patates',
    'carrot': 'havuç',
    'carrots': 'havuç',
    'lettuce': 'marul',
    'cucumber': 'salatalık',
    'cucumbers': 'salatalık',
    'bell pepper': 'biber',
    'bell peppers': 'biber',
    'mushroom': 'mantar',
    'mushrooms': 'mantar',
    'spinach': 'ıspanak',
    'lemon': 'limon',
    'lemons': 'limon',
    'lime': 'yeşil limon',
    'orange': 'portakal',
    'oranges': 'portakal',
    'apple': 'elma',
    'apples': 'elma',
    'banana': 'muz',
    'bananas': 'muz',
    'strawberry': 'çilek',
    'strawberries': 'çilek',
    'yogurt': 'yoğurt',
    'yoghurt': 'yoğurt',
    'honey': 'bal',
    'vinegar': 'sirke',
    'soy sauce': 'soya sosu',
    'oil': 'yağ',
    'vegetable oil': 'ayçiçek yağı',
    'sunflower oil': 'ayçiçek yağı',
    'cumin': 'kimyon',
    'paprika': 'kırmızı biber',
    'oregano': 'kekik',
    'basil': 'fesleğen',
    'parsley': 'maydanoz',
    'dried mint': 'kuru nane',
    'mint': 'nane',
    'cilantro': 'kişniş',
    'coriander': 'kişniş',
    'thyme': 'kekik',
    'rosemary': 'biberiye',
    'bay leaf': 'defne yaprağı',
    'bay leaves': 'defne yaprağı',
    'cinnamon': 'tarçın',
    'nutmeg': 'muskat',
    'ginger': 'zencefil',
    'turmeric': 'zerdeçal',
    'curry': 'köri',
    'chili': 'acı biber',
    'chili pepper': 'acı biber',
    'chili peppers': 'acı biber',
    'pepper flakes': 'pul biber',
    'red pepper flakes': 'pul biber',
    'chilli flakes': 'pul biber',
    'chili flakes': 'pul biber',
    'sesame': 'susam',
    'sesame seeds': 'susam',
    'almond': 'badem',
    'almonds': 'badem',
    'walnut': 'ceviz',
    'walnuts': 'ceviz',
    'hazelnut': 'fındık',
    'hazelnuts': 'fındık',
    'pistachio': 'antep fıstığı',
    'pistachios': 'antep fıstığı',
    'lentil': 'mercimek',
    'lentils': 'mercimek',
    'chickpea': 'nohut',
    'chickpeas': 'nohut',
    'bean': 'fasulye',
    'beans': 'fasulye',
    'green bean': 'taze fasulye',
    'green beans': 'taze fasulye',
    'broccoli': 'brokoli',
    'cauliflower': 'karnabahar',
    'cabbage': 'lahana',
    'zucchini': 'kabak',
    'eggplant': 'patlıcan',
    'aubergine': 'patlıcan',
    'corn': 'mısır',
    'peas': 'bezelye',
    'green peas': 'bezelye',
    'avocado': 'avokado',
    'avocados': 'avokado',
  };

  static String translate(String ingredientName) {
    final normalized = ingredientName.toLowerCase().trim();
    if (_translations.containsKey(normalized)) {
      return _translations[normalized]!;
    }
    for (final entry in _translations.entries) {
      if (normalized.contains(entry.key) || entry.key.contains(normalized)) {
        return entry.value;
      }
    }
    return ingredientName;
  }
}

